export interface EmpireInfo {
  name: string;
  capital?: string;
  government?: string;
  language?: string;
  religion?: string;
  founded?: string;
  collapsed?: string;
  peakArea?: string;
  leaders?: string[];
  summary: string;
  /** Larger polity this territory belonged to, if any (e.g. khanates under the Mongols). */
  partOf?: string;
  /** Year the sidebar auto-suggests scrubbing to, usually the polity's peak. */
  contextYear?: number;
}

// Keyed by the exact NAME property used in the historical-basemaps GeoJSON,
// so a click on a polygon can look its info straight up.
export const EMPIRES: Record<string, EmpireInfo> = {
  // ------------------------------------------------------------- Rome
  "Roman Empire": {
    name: "Roman Empire",
    capital: "Rome",
    government: "Empire",
    language: "Latin",
    religion: "Roman polytheism, later Christianity",
    founded: "27 BC",
    collapsed: "476 AD (West)",
    peakArea: "~5,000,000 km²",
    leaders: ["Augustus", "Trajan", "Marcus Aurelius", "Constantine I"],
    summary:
      "Grew from a small city-state into the dominant power of the Mediterranean, ruling through a mix of military conquest, engineering and law that still shapes the modern world.",
    contextYear: 117,
  },
  "Roman Republic": {
    name: "Roman Republic",
    capital: "Rome",
    government: "Republic",
    language: "Latin",
    founded: "509 BC",
    collapsed: "27 BC",
    leaders: ["Scipio Africanus", "Julius Caesar", "Cicero"],
    summary:
      "The city-state that toppled its kings and conquered Italy, then tore itself apart in civil war — the republic's fall produced the empire that inherited it.",
    contextYear: -100,
  },
  Rome: {
    name: "Rome",
    capital: "Rome",
    government: "City-state",
    language: "Latin",
    founded: "753 BC",
    summary:
      "A settlement on the Tiber that legend dates to 753 BC, and which grew — first as a kingdom, then a republic, then an empire — into the seat of the ancient Mediterranean's greatest power.",
    contextYear: -300,
  },
  "Western Roman Empire": {
    name: "Western Roman Empire",
    capital: "Ravenna",
    government: "Empire",
    language: "Latin",
    founded: "395 AD",
    collapsed: "476 AD",
    leaders: ["Honorius", "Valentinian III", "Romulus Augustulus"],
    summary:
      "The western half of the Roman Empire after the 395 split, worn down by economic strain and repeated incursions until its last emperor was deposed in 476.",
    partOf: "Roman Empire (before 395)",
    contextYear: 400,
  },
  "Eastern Roman Empire": {
    name: "Eastern Roman Empire",
    capital: "Constantinople",
    government: "Empire",
    language: "Greek, Latin",
    founded: "395 AD",
    collapsed: "1453 AD",
    leaders: ["Theodosius I", "Justinian I", "Heraclius"],
    summary:
      "The wealthier eastern half of the Roman Empire, which endured for a thousand years after Rome fell in the west and is known to historians as the Byzantine Empire.",
    partOf: "Roman Empire (before 395)",
    contextYear: 550,
  },
  "Byzantine Empire": {
    name: "Byzantine Empire",
    capital: "Constantinople",
    government: "Empire",
    language: "Greek",
    religion: "Eastern Orthodox Christianity",
    founded: "330 AD",
    collapsed: "1453 AD",
    peakArea: "~3,500,000 km²",
    leaders: ["Justinian I", "Basil II", "Constantine XI"],
    summary:
      "The continuation of Rome in the east, a fortress-capital civilization that preserved classical learning and Orthodox Christianity for a millennium before falling to the Ottomans.",
    contextYear: 1025,
  },
  "Ostrogoths": {
    name: "Ostrogothic Kingdom",
    capital: "Ravenna",
    government: "Kingdom",
    language: "Gothic, Latin",
    founded: "493 AD",
    collapsed: "553 AD",
    leaders: ["Theodoric the Great"],
    summary:
      "Theodoric's Goths took Italy from Odoacer and ruled in Rome's name, keeping Roman administration alive until Justinian's armies destroyed their kingdom in two decades of devastating war.",
    contextYear: 526,
  },
  "Visigoths": {
    name: "Visigothic Kingdom",
    capital: "Toledo",
    government: "Kingdom",
    language: "Gothic, Latin",
    founded: "418 AD",
    collapsed: "711 AD",
    leaders: ["Alaric I", "Leovigild"],
    summary:
      "The Goths who sacked Rome in 410 settled in Iberia and ruled it for three centuries, converting to Catholicism and codifying Roman law before falling to the Arab conquest.",
    contextYear: 600,
  },
  "Carthage": {
    name: "Carthage",
    capital: "Carthage",
    government: "Republic",
    language: "Punic",
    religion: "Punic polytheism",
    founded: "814 BC",
    collapsed: "146 BC",
    leaders: ["Hannibal", "Hamilcar Barca"],
    summary:
      "The Phoenician trading city whose maritime empire rivaled Rome across three Punic Wars, brought down at last by Scipio's legions and the total destruction of 146 BC.",
    contextYear: -200,
  },
  "Carthaginian Empire": {
    name: "Carthaginian Empire",
    capital: "Carthage",
    government: "Republic",
    language: "Punic",
    founded: "814 BC",
    collapsed: "146 BC",
    leaders: ["Hannibal", "Hamilcar Barca"],
    summary:
      "The Phoenician trading city whose maritime empire rivaled Rome across three Punic Wars, brought down at last by Scipio's legions and the total destruction of 146 BC.",
    contextYear: -200,
  },
  "Ptolemaic Kingdom": {
    name: "Ptolemaic Kingdom",
    capital: "Alexandria",
    government: "Hellenistic monarchy",
    language: "Greek, Egyptian",
    religion: "Ancient Egyptian religion, Hellenistic religion",
    founded: "305 BC",
    collapsed: "30 BC",
    leaders: ["Ptolemy I", "Cleopatra VII"],
    summary:
      "Alexander's general Ptolemy and his heirs ruled fabulously rich Egypt from Alexandria for three centuries, ending with Cleopatra's defeat at Actium.",
    partOf: "Diadochi kingdoms",
    contextYear: -250,
  },
  "Macedon and Hellenic League": {
    name: "Kingdom of Macedon",
    capital: "Pella",
    government: "Monarchy",
    language: "Ancient Greek",
    founded: "808 BC",
    collapsed: "148 BC",
    leaders: ["Philip II", "Alexander the Great"],
    summary:
      "The northern Greek kingdom of Philip II and his son Alexander, whose armies swept to the Indus in a decade and spread Greek culture across the known world.",
    contextYear: -323,
  },
  "Empire of Alexander": {
    name: "Empire of Alexander",
    capital: "Babylon, Pella",
    government: "Monarchy",
    language: "Ancient Greek",
    founded: "336 BC",
    collapsed: "323 BC",
    leaders: ["Alexander the Great"],
    summary:
      "The largest empire the world had yet seen, carved out in twelve years by Alexander of Macedon — and dissolved at his death into the quarrelling successor states.",
    contextYear: -323,
  },
  "Seleucid Kingdom": {
    name: "Seleucid Empire",
    capital: "Antioch, Seleucia",
    government: "Hellenistic monarchy",
    language: "Greek, Aramaic",
    founded: "312 BC",
    collapsed: "63 BC",
    leaders: ["Seleucus I", "Antiochus III"],
    summary:
      "The largest of the successor states to Alexander's empire, stretching from the Aegean to Afghanistan before being ground away by Rome and Parthia.",
    partOf: "Diadochi kingdoms",
    contextYear: -300,
  },
  "Achaemenid Empire": {
    name: "Achaemenid Empire",
    capital: "Persepolis, Susa, Babylon",
    government: "Imperial monarchy",
    language: "Old Persian, Aramaic",
    religion: "Zoroastrianism",
    founded: "550 BC",
    collapsed: "330 BC",
    peakArea: "~5,500,000 km²",
    leaders: ["Cyrus the Great", "Darius I", "Xerxes I"],
    summary:
      "The first true world empire, spanning three continents under the 'King of Kings', admired even by its enemies for its roads, satrapies and tolerance.",
    contextYear: -480,
  },
  // ------------------------------------------------------- East Asia
  Han: {
    name: "Han Empire",
    capital: "Chang'an / Luoyang",
    government: "Imperial dynasty",
    language: "Old Chinese",
    religion: "Confucianism, Taoism, folk religion",
    founded: "206 BC",
    collapsed: "220 AD",
    peakArea: "~6,000,000 km²",
    leaders: ["Emperor Gaozu", "Emperor Wu", "Emperor Guangwu"],
    summary:
      "One of the great classical empires, contemporaneous with Rome, whose bureaucracy, silk trade and cultural identity gave China's majority ethnic group its name.",
    contextYear: 100,
  },
  "Han Empire": {
    name: "Han Empire",
    capital: "Chang'an / Luoyang",
    government: "Imperial dynasty",
    language: "Old Chinese",
    religion: "Confucianism, Taoism, folk religion",
    founded: "206 BC",
    collapsed: "220 AD",
    peakArea: "~6,000,000 km²",
    leaders: ["Emperor Gaozu", "Emperor Wu", "Emperor Guangwu"],
    summary:
      "One of the great classical empires, contemporaneous with Rome, whose bureaucracy, silk trade and cultural identity gave China's majority ethnic group its name.",
    contextYear: 100,
  },
  Qin: {
    name: "Qin Empire",
    capital: "Xianyang",
    government: "Imperial dynasty",
    language: "Old Chinese",
    founded: "221 BC",
    collapsed: "206 BC",
    leaders: ["Qin Shi Huang"],
    summary:
      "The short-lived dynasty that first unified China, standardizing script, currency and axle-widths, building early Great Wall ramparts — and burying a terracotta army.",
    contextYear: -210,
  },
  "Tang Empire": {
    name: "Tang Empire",
    capital: "Chang'an",
    government: "Imperial dynasty",
    language: "Middle Chinese",
    religion: "Buddhism, Taoism, Confucianism",
    founded: "618 AD",
    collapsed: "907 AD",
    peakArea: "~5,400,000 km²",
    leaders: ["Emperor Taizong", "Empress Wu Zetian", "Emperor Xuanzong"],
    summary:
      "Often considered the high point of pre-modern Chinese civilization, with Chang'an as the largest city on Earth and cosmopolitan trade along the Silk Road.",
    contextYear: 750,
  },
  "Song Empire": {
    name: "Song Empire",
    capital: "Kaifeng, later Hangzhou",
    government: "Imperial dynasty",
    language: "Middle Chinese",
    founded: "960 AD",
    collapsed: "1279 AD",
    leaders: ["Emperor Taizu"],
    summary:
      "A dynasty of unparalleled economic and technological achievement — printing, gunpowder, the compass — yet militarily pressed from the north until the Mongols overran it.",
    contextYear: 1100,
  },
  "Ming Empire": {
    name: "Ming Empire",
    capital: "Nanjing, later Beijing",
    government: "Imperial dynasty",
    language: "Mandarin Chinese",
    religion: "Confucianism, Buddhism, Taoism",
    founded: "1368 AD",
    collapsed: "1644 AD",
    peakArea: "~6,500,000 km²",
    leaders: ["Hongwu Emperor", "Yongle Emperor"],
    summary:
      "Restored native Chinese rule after Mongol Yuan rule, building the Forbidden City and sending Zheng He's treasure fleets as far as East Africa.",
    contextYear: 1420,
  },
  "Ming Chinese Empire": {
    name: "Ming Empire",
    capital: "Beijing",
    government: "Imperial dynasty",
    language: "Mandarin Chinese",
    founded: "1368 AD",
    collapsed: "1644 AD",
    leaders: ["Yongle Emperor", "Wanli Emperor"],
    summary:
      "Restored native Chinese rule after Mongol Yuan rule, building the Forbidden City and sending Zheng He's treasure fleets as far as East Africa.",
    contextYear: 1420,
  },
  "Qing Empire": {
    name: "Qing Empire",
    capital: "Beijing",
    government: "Imperial dynasty",
    language: "Manchu, Mandarin Chinese",
    founded: "1644 AD",
    collapsed: "1912 AD",
    peakArea: "~13,100,000 km²",
    leaders: ["Kangxi Emperor", "Qianlong Emperor", "Puyi (last emperor)"],
    summary:
      "China's last imperial dynasty, founded by Manchu conquerors, which nearly tripled the territory of the Ming before collapsing into the 1912 republic.",
    contextYear: 1790,
  },
  "Yuan": {
    name: "Yuan dynasty",
    capital: "Khanbaliq (Beijing)",
    government: "Imperial dynasty",
    language: "Mongolian, Mandarin Chinese",
    founded: "1271 AD",
    collapsed: "1368 AD",
    leaders: ["Kublai Khan"],
    summary:
      "The Chinese dynasty founded by Kublai Khan, through which the Mongols ruled China proper — the era of Marco Polo's journey and of the Grand Canal's northern extension.",
    partOf: "Mongol Empire",
    contextYear: 1290,
  },
  "Xiongnu": {
    name: "Xiongnu Confederation",
    capital: "Nomadic (Orkhon valley)",
    government: "Nomadic confederation",
    language: "Uncertain (possibly Turkic or Mongolic)",
    founded: "209 BC",
    collapsed: "155 AD",
    leaders: ["Modu Chanyu"],
    summary:
      "The steppe confederation that first forced a unified China to build walls, extracting tribute through horse-archer raids for two and a half centuries.",
    contextYear: -150,
  },
  "Mongol Empire": {
    name: "Mongol Empire",
    capital: "Karakorum",
    government: "Nomadic empire",
    language: "Mongolian",
    religion: "Tengrism, later Buddhism and Islam",
    founded: "1206 AD",
    collapsed: "1368 AD",
    peakArea: "~24,000,000 km²",
    leaders: ["Genghis Khan", "Ögedei Khan", "Kublai Khan"],
    summary:
      "The largest contiguous land empire ever assembled, unified by Genghis Khan in 1206 and stretching from Korea to Hungary within a single lifetime.",
    contextYear: 1279,
  },
  Mongols: {
    name: "Mongol Empire",
    capital: "Karakorum",
    government: "Nomadic empire",
    language: "Mongolian",
    founded: "1206 AD",
    collapsed: "1368 AD",
    leaders: ["Genghis Khan", "Ögedei Khan", "Kublai Khan"],
    summary:
      "The largest contiguous land empire ever assembled, unified by Genghis Khan in 1206 and stretching from Korea to Hungary within a single lifetime.",
    contextYear: 1279,
  },
  "Golden Horde": {
    name: "Golden Horde",
    capital: "Sarai",
    government: "Khanate",
    language: "Mongolian, Kipchak Turkic",
    religion: "Tengrism, later Islam",
    founded: "1242 AD",
    collapsed: "1502 AD",
    leaders: ["Batu Khan"],
    summary:
      "The westernmost khanate of the Mongol Empire, ruling over Rus' principalities and the Pontic steppe for over two centuries.",
    partOf: "Mongol Empire",
    contextYear: 1310,
  },
  "Khanate of the Golden Horde": {
    name: "Golden Horde",
    capital: "Sarai",
    government: "Khanate",
    language: "Mongolian, Kipchak Turkic",
    founded: "1242 AD",
    collapsed: "1502 AD",
    leaders: ["Batu Khan"],
    summary:
      "The westernmost khanate of the Mongol Empire, ruling over Rus' principalities and the Pontic steppe for over two centuries.",
    partOf: "Mongol Empire",
    contextYear: 1310,
  },
  "Ilkhanate": {
    name: "Ilkhanate",
    capital: "Tabriz, later Soltaniyeh",
    government: "Khanate",
    language: "Mongolian, Persian",
    religion: "Tengrism, Buddhism, later Islam",
    founded: "1256 AD",
    collapsed: "1335 AD",
    leaders: ["Hulagu Khan", "Ghazan"],
    summary:
      "The Mongol khanate of Persia, which sacked Baghdad in 1258 and later embraced Islam and Persian court culture.",
    partOf: "Mongol Empire",
    contextYear: 1290,
  },
  "Chagatai Khanate": {
    name: "Chagatai Khanate",
    capital: "Almaliq",
    government: "Khanate",
    language: "Mongolian, Chagatai Turkic",
    founded: "1227 AD",
    collapsed: "1687 AD",
    leaders: ["Chagatai Khan"],
    summary:
      "The central Asian khanate ruled by Genghis Khan's second son's line, later split into settled Transoxiana and the nomadic Moghulistan.",
    partOf: "Mongol Empire",
    contextYear: 1300,
  },
  "Great Khanate": {
    name: "Great Khanate",
    capital: "Khanbaliq (Beijing)",
    government: "Khanate / Imperial dynasty",
    language: "Mongolian, Mandarin Chinese",
    founded: "1260 AD",
    collapsed: "1368 AD",
    leaders: ["Kublai Khan"],
    summary:
      "The senior line of Genghis Khan's descendants under Kublai, who claimed rule over all Mongol lands while actually governing China as the Yuan dynasty.",
    partOf: "Mongol Empire",
    contextYear: 1290,
  },
  // ------------------------------------------------------- Persia & Caliphates
  "Parthian Empire": {
    name: "Parthian Empire",
    capital: "Ctesiphon",
    government: "Feudal monarchy",
    language: "Parthian, Aramaic",
    religion: "Zoroastrianism",
    founded: "247 BC",
    collapsed: "224 AD",
    peakArea: "~2,800,000 km²",
    leaders: ["Mithridates I", "Mithridates II", "Orodes II"],
    summary:
      "Rome's great eastern rival, controlling the trade routes of the Iranian plateau and famous for the horse archers that humiliated Crassus at Carrhae.",
    contextYear: -50,
  },
  Parthia: {
    name: "Parthian Empire",
    capital: "Ctesiphon",
    government: "Feudal monarchy",
    language: "Parthian, Aramaic",
    religion: "Zoroastrianism",
    founded: "247 BC",
    collapsed: "224 AD",
    leaders: ["Mithridates I", "Mithridates II", "Orodes II"],
    summary:
      "Rome's great eastern rival, controlling the trade routes of the Iranian plateau and famous for the horse archers that humiliated Crassus at Carrhae.",
    contextYear: -50,
  },
  "Sasanian Empire": {
    name: "Sasanian Empire",
    capital: "Ctesiphon",
    government: "Imperial monarchy",
    language: "Middle Persian",
    religion: "Zoroastrianism",
    founded: "224 AD",
    collapsed: "651 AD",
    peakArea: "~3,500,000 km²",
    leaders: ["Ardashir I", "Khosrow I", "Khosrow II"],
    summary:
      "The last pre-Islamic Persian empire, a cultural and military superpower whose long wars with Byzantium exhausted both sides just before the Arab conquests.",
    contextYear: 620,
  },
  "Umayyad Caliphate": {
    name: "Umayyad Caliphate",
    capital: "Damascus",
    government: "Hereditary caliphate",
    language: "Arabic",
    religion: "Islam",
    founded: "661 AD",
    collapsed: "750 AD",
    peakArea: "~11,100,000 km²",
    leaders: ["Muawiyah I", "Abd al-Malik"],
    summary:
      "The first hereditary caliphate, which expanded Islamic rule from Spain to Central Asia faster than almost any empire in history before being overthrown by the Abbasids.",
    contextYear: 750,
  },
  "Abbasid Caliphate": {
    name: "Abbasid Caliphate",
    capital: "Baghdad",
    government: "Caliphate",
    language: "Arabic, Persian",
    religion: "Islam",
    founded: "750 AD",
    collapsed: "1258 AD",
    peakArea: "~11,000,000 km²",
    leaders: ["Al-Mansur", "Harun al-Rashid", "Al-Ma'mun"],
    summary:
      "Shifted the center of the Islamic world to Baghdad and presided over the Islamic Golden Age, translating and expanding on Greek, Persian and Indian scholarship.",
    contextYear: 800,
  },
  "Fatimid Caliphate": {
    name: "Fatimid Caliphate",
    capital: "Mahdia, later Cairo",
    government: "Caliphate",
    language: "Arabic",
    religion: "Ismaili Shia Islam",
    founded: "909 AD",
    collapsed: "1171 AD",
    leaders: ["al-Mahdi", "al-Hakim", "Saladin (conqueror)"],
    summary:
      "The Shia caliphate that founded Cairo and al-Azhar, rivaling the Abbasids for the soul of the Islamic world and ruling Egypt at its medieval zenith.",
    contextYear: 1000,
  },
  "Almohad Caliphate": {
    name: "Almohad Caliphate",
    capital: "Marrakesh, later Seville",
    government: "Caliphate",
    language: "Arabic, Berber",
    religion: "Islam",
    founded: "1121 AD",
    collapsed: "1269 AD",
    leaders: ["Ibn Tumart", "Yaqub al-Mansur"],
    summary:
      "The Berber caliphate that united North Africa and al-Andalus, erecting the Koutoubia and Giralda, before fragmenting under Christian Reconquista pressure.",
    contextYear: 1200,
  },
  "Almoravid dynasty": {
    name: "Almoravid dynasty",
    capital: "Marrakesh",
    government: "Empire",
    language: "Berber, Arabic",
    religion: "Islam",
    founded: "1040 AD",
    collapsed: "1147 AD",
    leaders: ["Yusuf ibn Tashfin"],
    summary:
      "Sanhaja Berber reformers who built an empire from the Sahara to the Ebro, halting the Reconquista at the Battle of Sagrajas and ruling al-Andalus for a century.",
    contextYear: 1100,
  },
  "Caliphate of Córdoba": {
    name: "Caliphate of Córdoba",
    capital: "Córdoba",
    government: "Caliphate",
    language: "Arabic, Andalusian Romance",
    religion: "Islam, Christianity, Judaism",
    founded: "929 AD",
    collapsed: "1031 AD",
    leaders: ["Abd al-Rahman III", "Almanzor"],
    summary:
      "Islamic Spain at its dazzling height — Córdoba was Europe's largest city, famous for its libraries, physicians and the Great Mosque.",
    contextYear: 1000,
  },
  // ------------------------------------------------------------- India
  "Mauryan Empire": {
    name: "Mauryan Empire",
    capital: "Pataliputra",
    government: "Empire",
    language: "Magadhi Prakrit",
    religion: "Hinduism, later Buddhism under Ashoka",
    founded: "322 BC",
    collapsed: "185 BC",
    peakArea: "~5,000,000 km²",
    leaders: ["Chandragupta Maurya", "Ashoka the Great"],
    summary:
      "The first empire to unify nearly the entire Indian subcontinent, reaching its moral and territorial peak under Ashoka, who embraced Buddhism after the bloody conquest of Kalinga.",
    contextYear: -250,
  },
  "Gupta Empire": {
    name: "Gupta Empire",
    capital: "Pataliputra",
    government: "Empire",
    language: "Sanskrit",
    religion: "Hinduism, Buddhism",
    founded: "320 AD",
    collapsed: "550 AD",
    leaders: ["Chandragupta I", "Samudragupta", "Chandragupta II"],
    summary:
      "Presided over a golden age of Indian science, mathematics and art, including the concept of zero and the foundations of classical Sanskrit literature.",
    contextYear: 440,
  },
  "Mughal Empire": {
    name: "Mughal Empire",
    capital: "Agra, later Delhi",
    government: "Empire",
    language: "Persian, Hindustani",
    religion: "Islam, Hinduism (majority)",
    founded: "1526 AD",
    collapsed: "1857 AD",
    peakArea: "~4,000,000 km²",
    leaders: ["Babur", "Akbar", "Aurangzeb"],
    summary:
      "Descendants of Timur and Genghis Khan who built one of the wealthiest empires in history across the Indian subcontinent, patrons of the Taj Mahal.",
    contextYear: 1700,
  },
  "Sultanate of Delhi": {
    name: "Delhi Sultanate",
    capital: "Delhi",
    government: "Sultanate",
    language: "Persian",
    religion: "Islam",
    founded: "1206 AD",
    collapsed: "1526 AD",
    leaders: ["Iltutmish", "Alauddin Khalji"],
    summary:
      "Five successive dynasties of Turkic and Afghan origin ruled northern India from Delhi for three centuries, resisting the Mongols and commissioning the Qutb Minar.",
    contextYear: 1310,
  },
  "Chola": {
    name: "Chola Empire",
    capital: "Thanjavur",
    government: "Monarchy",
    language: "Tamil",
    religion: "Hinduism",
    founded: "300s BC",
    collapsed: "1279 AD",
    leaders: ["Rajaraja I", "Rajendra I"],
    summary:
      "The maritime empire of the Tamil south, whose fleets crossed to Srivijaya and whose bronze temples defined South Indian art.",
    contextYear: 1030,
  },
  Cholas: {
    name: "Chola Empire",
    capital: "Thanjavur",
    government: "Monarchy",
    language: "Tamil",
    religion: "Hinduism",
    founded: "300s BC",
    collapsed: "1279 AD",
    leaders: ["Rajaraja I", "Rajendra I"],
    summary:
      "The maritime empire of the Tamil south, whose fleets crossed to Srivijaya and whose bronze temples defined South Indian art.",
    contextYear: 1030,
  },
  "Kushan Empire": {
    name: "Kushan Empire",
    capital: "Peshawar, Mathura",
    government: "Empire",
    language: "Bactrian, Gandhari Prakrit",
    religion: "Buddhism, Hinduism, Zoroastrianism",
    founded: "30 AD",
    collapsed: "375 AD",
    leaders: ["Kanishka the Great"],
    summary:
      "A Silk Road empire at the crossroads of China, India and Rome whose patronage carried Gandharan Buddhist art along the trade routes.",
    contextYear: 130,
  },
  // ------------------------------------------------------- SE Asia & steppe
  "Khmer Empire": {
    name: "Khmer Empire",
    capital: "Angkor",
    government: "Empire",
    language: "Old Khmer, Sanskrit",
    religion: "Hinduism, Mahayana Buddhism",
    founded: "802 AD",
    collapsed: "1431 AD",
    leaders: ["Jayavarman II", "Suryavarman II", "Jayavarman VII"],
    summary:
      "Southeast Asia's great temple-building civilization, responsible for Angkor Wat, once the largest urban settlement on Earth.",
    contextYear: 1200,
  },
  "Srivijaya Empire": {
    name: "Srivijaya Empire",
    capital: "Palembang",
    government: "Maritime empire",
    language: "Old Malay",
    religion: "Mahayana Buddhism",
    founded: "650 AD",
    collapsed: "1200s AD",
    leaders: ["Sri Jayanasa"],
    summary:
      "A maritime trading empire that controlled the Strait of Malacca for centuries, spreading Buddhism across the Malay archipelago.",
    contextYear: 850,
  },
  "Göktürks": {
    name: "Göktürk Khaganate",
    capital: "Ötüken (nomadic)",
    government: "Khaganate",
    language: "Old Turkic",
    religion: "Tengrism",
    founded: "552 AD",
    collapsed: "744 AD",
    leaders: ["Bumin Qaghan", "Tardu"],
    summary:
      "The first Turkic empire, stretching from Manchuria to the Black Sea, whose Orkhon inscriptions are the earliest written record of any Turkic language.",
    contextYear: 600,
  },
  "Avars": {
    name: "Avar Khaganate",
    capital: "The Ring (Pannonia)",
    government: "Khaganate",
    language: "Avar (uncertain), Turkic",
    founded: "567 AD",
    collapsed: "822 AD",
    leaders: ["Bayan I"],
    summary:
      "Horse-nomads who fled the Turks westward into Pannonia and built a khaganate that raided Byzantium and Charlemagne's Franks for two centuries.",
    contextYear: 600,
  },
  "Huns": {
    name: "Hunnic Empire",
    capital: "Nomadic",
    government: "Tribal confederation",
    language: "Hunnic (uncertain)",
    founded: "370 AD",
    collapsed: "469 AD",
    leaders: ["Attila", "Bleda"],
    summary:
      "The mounted confederation that burst out of the steppe and pushed Germanic peoples into the Roman Empire, reaching its terror-height under Attila.",
    contextYear: 450,
  },
  "Hunnic Empire": {
    name: "Hunnic Empire",
    capital: "Nomadic",
    government: "Tribal confederation",
    language: "Hunnic (uncertain)",
    founded: "370 AD",
    collapsed: "469 AD",
    leaders: ["Attila", "Bleda"],
    summary:
      "The mounted confederation that burst out of the steppe and pushed Germanic peoples into the Roman Empire, reaching its terror-height under Attila.",
    contextYear: 450,
  },
  "Timurid Empire": {
    name: "Timurid Empire",
    capital: "Samarkand, Herat",
    government: "Empire",
    language: "Persian, Chagatai Turkic",
    religion: "Islam",
    founded: "1370 AD",
    collapsed: "1507 AD",
    leaders: ["Timur (Tamerlane)", "Shah Rukh"],
    summary:
      "Built by the conqueror Timur, who claimed descent from Genghis Khan, and later flourished as a center of Persianate art, science and astronomy.",
    contextYear: 1405,
  },
  // ------------------------------------------------------- Europe medieval
  "Carolingian Empire": {
    name: "Carolingian Empire",
    capital: "Aachen",
    government: "Empire",
    language: "Latin, Old Frankish",
    religion: "Catholic Christianity",
    founded: "800 AD",
    collapsed: "888 AD",
    leaders: ["Charlemagne", "Louis the Pious"],
    summary:
      "Briefly reunited most of Western Europe under Charlemagne, who was crowned Roman Emperor by the Pope in 800, laying cultural groundwork for medieval Europe.",
    contextYear: 814,
  },
  "Frankish Kingdom": {
    name: "Frankish Kingdom",
    capital: "Aachen, Paris",
    government: "Kingdom",
    language: "Old Frankish, Latin",
    religion: "Catholic Christianity",
    founded: "481 AD",
    collapsed: "843 AD",
    leaders: ["Clovis I", "Charles Martel", "Charlemagne"],
    summary:
      "The Germanic kingdom that inherited Roman Gaul, halted the Umayyads at Tours, and grew into the Carolingian empire of Charlemagne.",
    contextYear: 780,
  },
  Franks: {
    name: "Frankish Kingdom",
    capital: "Aachen, Paris",
    government: "Kingdom",
    language: "Old Frankish, Latin",
    religion: "Catholic Christianity",
    founded: "481 AD",
    collapsed: "843 AD",
    leaders: ["Clovis I", "Charles Martel", "Charlemagne"],
    summary:
      "The Germanic kingdom that inherited Roman Gaul, halted the Umayyads at Tours, and grew into the Carolingian empire of Charlemagne.",
    contextYear: 780,
  },
  "Holy Roman Empire": {
    name: "Holy Roman Empire",
    capital: "No fixed capital (Aachen, Regensburg, Vienna)",
    government: "Elective confederation",
    language: "German, Latin",
    religion: "Catholic Christianity",
    founded: "800 / 962 AD",
    collapsed: "1806 AD",
    leaders: ["Otto I", "Frederick Barbarossa", "Charles V"],
    summary:
      "A loose, elective confederation of Central European states under an emperor — famously neither holy, nor Roman, nor much of an empire, yet it endured for a thousand years.",
    contextYear: 1600,
  },
  "Angevin Empire": {
    name: "Angevin Empire",
    capital: "No fixed capital (Rouenne, Chinon)",
    government: "Composite monarchy",
    language: "Old French, Anglo-Norman",
    religion: "Catholic Christianity",
    founded: "1154 AD",
    collapsed: "1214 AD",
    leaders: ["Henry II", "Richard the Lionheart", "John"],
    summary:
      "The Plantagenet holding that stretched from Scotland to the Pyrenees — half of France ruled from England's throne — until Philip II of France clawed it apart.",
    contextYear: 1180,
  },
  "Kievan Rus": {
    name: "Kievan Rus'",
    capital: "Kiev",
    government: "Principality federation",
    language: "Old East Slavic",
    religion: "Eastern Orthodox Christianity (from 988)",
    founded: "882 AD",
    collapsed: "1240 AD",
    leaders: ["Oleg of Novgorod", "Vladimir the Great", "Yaroslav the Wise"],
    summary:
      "The federation of East Slavic principalities that adopted Orthodox Christianity and wrote the first laws of what became Russia, Ukraine and Belarus.",
    contextYear: 1000,
  },
  "Kyivan Rus": {
    name: "Kyivan Rus'",
    capital: "Kyiv",
    government: "Principality federation",
    language: "Old East Slavic",
    religion: "Eastern Orthodox Christianity (from 988)",
    founded: "882 AD",
    collapsed: "1240 AD",
    leaders: ["Oleg of Novgorod", "Vladimir the Great", "Yaroslav the Wise"],
    summary:
      "The federation of East Slavic principalities that adopted Orthodox Christianity and wrote the first laws of what became Russia, Ukraine and Belarus.",
    contextYear: 1000,
  },
  "Byzantine Sultanate": {
    name: "Byzantine Empire",
    capital: "Constantinople",
    government: "Empire",
    language: "Greek",
    religion: "Eastern Orthodox Christianity",
    founded: "330 AD",
    collapsed: "1453 AD",
    leaders: ["Justinian I", "Basil II", "Constantine XI"],
    summary:
      "The continuation of Rome in the east, a fortress-capital civilization that preserved classical learning and Orthodox Christianity for a millennium before falling to the Ottomans.",
    contextYear: 1025,
  },
  "Visigothic Kingdom": {
    name: "Visigothic Kingdom",
    capital: "Toledo",
    government: "Kingdom",
    language: "Gothic, Latin",
    founded: "418 AD",
    collapsed: "711 AD",
    leaders: ["Alaric I", "Leovigild"],
    summary:
      "The Goths who sacked Rome in 410 settled in Iberia and ruled it for three centuries, converting to Catholicism and codifying Roman law before falling to the Arab conquest.",
    contextYear: 600,
  },
  "Kingdom of Asturias": {
    name: "Kingdom of Asturias",
    capital: "Oviedo",
    government: "Kingdom",
    language: "Medieval Latin, Asturian",
    religion: "Catholic Christianity",
    founded: "718 AD",
    collapsed: "924 AD",
    leaders: ["Pelagius of Asturias", "Alfonso II"],
    summary:
      "The Christian refuge in the Cantabrian mountains that held out against the Umayyads and began the Reconquista after the victory at Covadonga.",
    contextYear: 800,
  },
  Asturias: {
    name: "Kingdom of Asturias",
    capital: "Oviedo",
    government: "Kingdom",
    language: "Medieval Latin, Asturian",
    religion: "Catholic Christianity",
    founded: "718 AD",
    collapsed: "924 AD",
    leaders: ["Pelagius of Asturias", "Alfonso II"],
    summary:
      "The Christian refuge in the Cantabrian mountains that held out against the Umayyads and began the Reconquista after the victory at Covadonga.",
    contextYear: 800,
  },
  Castile: {
    name: "Crown of Castile",
    capital: "Toledo, later Valladolid",
    government: "Kingdom",
    language: "Castilian Spanish",
    religion: "Catholic Christianity",
    founded: "1035 AD",
    collapsed: "1716 AD",
    leaders: ["Isabella I", "Ferdinand III"],
    summary:
      "The Castilian crown that drove the Reconquista to its end at Granada and, joined with Aragon, launched Spain's global empire.",
    contextYear: 1490,
  },
  Castilla: {
    name: "Crown of Castile",
    capital: "Toledo, later Valladolid",
    government: "Kingdom",
    language: "Castilian Spanish",
    religion: "Catholic Christianity",
    founded: "1035 AD",
    collapsed: "1716 AD",
    leaders: ["Isabella I", "Ferdinand III"],
    summary:
      "The Castilian crown that drove the Reconquista to its end at Granada and, joined with Aragon, launched Spain's global empire.",
    contextYear: 1490,
  },
  Castille: {
    name: "Crown of Castile",
    capital: "Toledo, later Valladolid",
    government: "Kingdom",
    language: "Castilian Spanish",
    religion: "Catholic Christianity",
    founded: "1035 AD",
    collapsed: "1716 AD",
    leaders: ["Isabella I", "Ferdinand III"],
    summary:
      "The Castilian crown that drove the Reconquista to its end at Granada and, joined with Aragon, launched Spain's global empire.",
    contextYear: 1490,
  },
  Aragón: {
    name: "Crown of Aragon",
    capital: "Zaragoza, later Barcelona",
    government: "Composite monarchy",
    language: "Aragonese, Catalan",
    religion: "Catholic Christianity",
    founded: "1035 AD",
    collapsed: "1716 AD",
    leaders: ["James I the Conqueror", "Ferdinand II"],
    summary:
      "A Mediterranean trading crown — Barcelona, Valencia, Sicily, Sardinia, Naples — whose union with Castile created Spain.",
    contextYear: 1450,
  },
  "Venice": {
    name: "Republic of Venice",
    capital: "Venice",
    government: "Merchant republic",
    language: "Venetian, Latin",
    religion: "Catholic Christianity",
    founded: "697 AD",
    collapsed: "1797 AD",
    leaders: ["Enrico Dandolo", "Francesco Foscari"],
    summary:
      "The Serenissima — a lagoon city that ruled the eastern Mediterranean's trade for a thousand years, from the Fourth Crusade's hijack to Canaletto's canvases.",
    contextYear: 1400,
  },
  "Genoa": {
    name: "Republic of Genoa",
    capital: "Genoa",
    government: "Merchant republic",
    language: "Ligurian, Latin",
    religion: "Catholic Christianity",
    founded: "1005 AD",
    collapsed: "1797 AD",
    leaders: ["Andrea Doria"],
    summary:
      "Venice's great rival, banker to the Spanish crown, home of Columbus — a city-state whose admirals and merchants quartered the Mediterranean.",
    contextYear: 1400,
  },
  "Papal States": {
    name: "Papal States",
    capital: "Rome",
    government: "Elective theocracy",
    language: "Latin, Italian",
    religion: "Catholic Christianity",
    founded: "756 AD",
    collapsed: "1870 AD",
    leaders: ["Pope Leo III", "Pope Julius II"],
    summary:
      "A band of central Italy ruled directly by the Popes, which made Rome a sovereign capital and Europe's papacy a temporal prince for eleven centuries.",
    contextYear: 1500,
  },
  "Grand Duchy of Moscow": {
    name: "Grand Duchy of Moscow",
    capital: "Moscow",
    government: "Grand duchy",
    language: "Old East Slavic",
    religion: "Eastern Orthodox Christianity",
    founded: "1283 AD",
    collapsed: "1547 AD",
    leaders: ["Ivan III the Great", "Ivan IV the Terrible"],
    summary:
      "The Muscovite principality that collected the fragmented Rus' lands, threw off the 'Tatar yoke' at the Ugra in 1480, and styled itself the Third Rome.",
    partOf: "Golden Horde (tributary)",
    contextYear: 1500,
  },
  "Tsardom of Muscovy": {
    name: "Tsardom of Russia",
    capital: "Moscow",
    government: "Tsardom",
    language: "Old East Slavic",
    religion: "Eastern Orthodox Christianity",
    founded: "1547 AD",
    collapsed: "1721 AD",
    leaders: ["Ivan IV the Terrible", "Michael Romanov"],
    summary:
      "The realm proclaimed when Ivan IV crowned himself Tsar — expanding through the Kazan and Siberian conquests into the largest state on Earth before Peter's empire.",
    contextYear: 1650,
  },
  "Russian Empire": {
    name: "Russian Empire",
    capital: "Saint Petersburg",
    government: "Absolute monarchy",
    language: "Russian",
    religion: "Eastern Orthodox Christianity",
    founded: "1721 AD",
    collapsed: "1917 AD",
    peakArea: "~22,800,000 km²",
    leaders: ["Peter the Great", "Catherine the Great", "Nicholas II"],
    summary:
      "Expanded from Muscovy into the largest contiguous empire in modern history, spanning Eastern Europe to the Pacific, ended by the 1917 revolution.",
    contextYear: 1866,
  },
  "Poland-Lithuania": {
    name: "Polish–Lithuanian Commonwealth",
    capital: "Kraków, later Warsaw",
    government: "Elective monarchy",
    language: "Polish, Lithuanian, Latin",
    religion: "Catholic Christianity",
    founded: "1569 AD",
    collapsed: "1795 AD",
    peakArea: "~1,000,000 km²",
    leaders: ["Sigismund II Augustus", "Jan III Sobieski"],
    summary:
      "Europe's largest and most tolerant state for two centuries — an elected king, a golden nobility, and a winged-hussar army — before it was partitioned out of existence.",
    contextYear: 1650,
  },
  "Polish–Lithuanian Commonwealth": {
    name: "Polish–Lithuanian Commonwealth",
    capital: "Kraków, later Warsaw",
    government: "Elective monarchy",
    language: "Polish, Lithuanian, Latin",
    religion: "Catholic Christianity",
    founded: "1569 AD",
    collapsed: "1795 AD",
    peakArea: "~1,000,000 km²",
    leaders: ["Sigismund II Augustus", "Jan III Sobieski"],
    summary:
      "Europe's largest and most tolerant state for two centuries — an elected king, a golden nobility, and a winged-hussar army — before it was partitioned out of existence.",
    contextYear: 1650,
  },
  "Ottoman Empire": {
    name: "Ottoman Empire",
    capital: "Istanbul (Constantinople)",
    government: "Absolute monarchy / Caliphate",
    language: "Ottoman Turkish",
    religion: "Islam (Sunni), with Orthodox Christian millets",
    founded: "1299 AD",
    collapsed: "1922 AD",
    peakArea: "~5,200,000 km²",
    leaders: ["Osman I", "Mehmed II", "Suleiman the Magnificent"],
    summary:
      "Rose from a small Anatolian principality to conquer Constantinople in 1453 and rule three continents, becoming one of the longest-lived empires in history.",
    contextYear: 1683,
  },
  "Ottoman Sultanate": {
    name: "Ottoman Empire",
    capital: "Istanbul",
    government: "Absolute monarchy",
    language: "Ottoman Turkish",
    religion: "Islam (Sunni)",
    founded: "1299 AD",
    collapsed: "1922 AD",
    leaders: ["Mehmed II", "Suleiman the Magnificent"],
    summary:
      "In its final decades, the once-vast Ottoman state — the 'Sick Man of Europe' — before its dissolution after the First World War.",
    contextYear: 1900,
  },
  "Austria Hungary": {
    name: "Austria-Hungary",
    capital: "Vienna / Budapest",
    government: "Dual monarchy",
    language: "German, Hungarian, Czech and a dozen others",
    religion: "Catholic Christianity",
    founded: "1867 AD",
    collapsed: "1918 AD",
    leaders: ["Franz Joseph I"],
    summary:
      "A dual monarchy joining Austrian and Hungarian crowns, one of Europe's great powers until it fractured along ethnic lines at the end of World War I.",
    contextYear: 1910,
  },
  "Austrian Empire": {
    name: "Austrian Empire",
    capital: "Vienna",
    government: "Absolute monarchy",
    language: "German, Hungarian, Czech and a dozen others",
    religion: "Catholic Christianity",
    founded: "1804 AD",
    collapsed: "1867 AD",
    leaders: ["Francis I", "Metternich"],
    summary:
      "The Habsburg realm reorganized as a formal empire in response to Napoleon, later transformed into Austria-Hungary in 1867.",
    contextYear: 1815,
  },
  "German Empire": {
    name: "German Empire",
    capital: "Berlin",
    government: "Federal semi-constitutional monarchy",
    language: "German",
    religion: "Protestant Christianity, Catholic Christianity",
    founded: "1871 AD",
    collapsed: "1918 AD",
    leaders: ["Wilhelm I", "Otto von Bismarck", "Wilhelm II"],
    summary:
      "Bismarck's unification of the German states under Prussia created the industrial powerhouse of Europe — and the alliance system that dragged it into world war.",
    contextYear: 1910,
  },
  Prussia: {
    name: "Kingdom of Prussia",
    capital: "Berlin, Königsberg",
    government: "Kingdom",
    language: "German",
    religion: "Protestant Christianity",
    founded: "1701 AD",
    collapsed: "1918 AD",
    leaders: ["Frederick the Great", "Otto von Bismarck"],
    summary:
      "The disciplined military state that unified Germany — the army of Frederick the Great 'not a country with an army, but an army with a country'.",
    contextYear: 1780,
  },
  France: {
    name: "France",
    capital: "Paris",
    government: "Varied (kingdom, republic, empire)",
    language: "French",
    religion: "Catholic Christianity",
    founded: "843 AD",
    leaders: ["Charlemagne (Frankish)", "Louis XIV", "Napoleon"],
    summary:
      "One of Europe's oldest continuous states, evolving from a medieval kingdom into a revolutionary republic and, briefly under Napoleon, an empire that dominated the continent.",
    contextYear: 1810,
  },
  "Kingdom of France": {
    name: "Kingdom of France",
    capital: "Paris",
    government: "Absolute monarchy",
    language: "French",
    religion: "Catholic Christianity",
    founded: "843 AD",
    collapsed: "1792 AD",
    leaders: ["Louis IX", "Louis XIV", "Louis XVI"],
    summary:
      "The medieval and early-modern French kingdom that grew from the Île-de-France into Europe's most populous and cultured power before the Revolution swept it away.",
    contextYear: 1780,
  },
  Spain: {
    name: "Spain",
    capital: "Madrid",
    government: "Varied (kingdom, republic)",
    language: "Spanish",
    religion: "Catholic Christianity",
    founded: "1479 AD",
    leaders: ["Ferdinand & Isabella", "Charles V", "Philip II"],
    summary:
      "United under the Catholic Monarchs in 1492, Spain built the first global empire, controlling territory across the Americas, Europe and the Pacific.",
    contextYear: 1600,
  },
  Portugal: {
    name: "Portugal",
    capital: "Lisbon",
    government: "Kingdom",
    language: "Portuguese",
    religion: "Catholic Christianity",
    founded: "1139 AD",
    leaders: ["Henry the Navigator", "Vasco da Gama"],
    summary:
      "Europe's first global sea empire — the caravels that rounded Africa to India, and the oldest fixed borders on the continent.",
    contextYear: 1500,
  },
  England: {
    name: "Kingdom of England",
    capital: "London, Winchester",
    government: "Monarchy",
    language: "Old/Middle English, Anglo-Norman",
    religion: "Catholic Christianity",
    founded: "927 AD",
    collapsed: "1707 AD",
    leaders: ["Alfred the Great", "William the Conqueror", "Elizabeth I"],
    summary:
      "The unified Anglo-Saxon kingdom, conquered by the Normans in 1066 and welded into the naval and parliamentary power that became Great Britain.",
    contextYear: 1600,
  },
  Scotland: {
    name: "Kingdom of Scotland",
    capital: "Edinburgh, Scone",
    government: "Monarchy",
    language: "Scots, Scottish Gaelic",
    religion: "Catholic Christianity, later Presbyterian",
    founded: "843 AD",
    collapsed: "1707 AD",
    leaders: ["Robert the Bruce", "Mary Queen of Scots"],
    summary:
      "The kingdom above Hadrian's Wall that fought off Edward I's conquest, and in 1707 entered union with England to form Great Britain.",
    contextYear: 1320,
  },
  // ------------------------------------------------------- Americas
  "Aztec Empire": {
    name: "Aztec Empire",
    capital: "Tenochtitlan",
    government: "Triple Alliance",
    language: "Classical Nahuatl",
    religion: "Aztec religion",
    founded: "1428 AD",
    collapsed: "1521 AD",
    peakArea: "~220,000 km²",
    leaders: ["Itzcoatl", "Moctezuma II"],
    summary:
      "A triple alliance of city-states centered on the lake-built capital of Tenochtitlan, ended abruptly by Hernán Cortés and Spanish conquest in 1521.",
    contextYear: 1520,
  },
  "Mexihcah (Triple Alliance)": {
    name: "Aztec Empire",
    capital: "Tenochtitlan",
    government: "Triple Alliance",
    language: "Classical Nahuatl",
    religion: "Aztec religion",
    founded: "1428 AD",
    collapsed: "1521 AD",
    leaders: ["Itzcoatl", "Moctezuma II"],
    summary:
      "A triple alliance of city-states centered on the lake-built capital of Tenochtitlan, ended abruptly by Hernán Cortés and Spanish conquest in 1521.",
    contextYear: 1520,
  },
  "Inca Empire": {
    name: "Inca Empire",
    capital: "Cusco",
    government: "Empire (Tawantinsuyu)",
    language: "Quechua",
    religion: "Inca religion (Inti worship)",
    founded: "1438 AD",
    collapsed: "1533 AD",
    peakArea: "~2,000,000 km²",
    leaders: ["Pachacuti", "Huayna Capac", "Atahualpa"],
    summary:
      "The largest empire in pre-Columbian America, linked by an extraordinary road network through the Andes, conquered by Francisco Pizarro in the 1530s.",
    contextYear: 1527,
  },
  Maya: {
    name: "Maya city-states",
    capital: "No fixed capital (Tikal, Calakmul, Copán)",
    government: "City-states",
    language: "Mayan languages",
    religion: "Maya religion",
    founded: "~2000 BC",
    collapsed: "900 AD (Classic south), 1697 AD (last kingdom)",
    summary:
      "A constellation of competing city-states sharing script, calendar and cosmology, whose mathematicians tracked Venus and whose glyphs are still being read today.",
    contextYear: 700,
  },
  "Maya city-states": {
    name: "Maya city-states",
    capital: "No fixed capital (Tikal, Calakmul, Copán)",
    government: "City-states",
    language: "Mayan languages",
    religion: "Maya religion",
    founded: "~2000 BC",
    collapsed: "900 AD (Classic south), 1697 AD (last kingdom)",
    summary:
      "A constellation of competing city-states sharing script, calendar and cosmology, whose mathematicians tracked Venus and whose glyphs are still being read today.",
    contextYear: 700,
  },
  Olmec: {
    name: "Olmec",
    capital: "San Lorenzo, La Venta",
    government: "Chiefdoms",
    language: "Uncertain (Mixe-Zoquean?)",
    founded: "1600 BC",
    collapsed: "400 BC",
    summary:
      "Mesoamerica's 'mother culture' — the colossal stone heads, early writing and ballgame that seeded later Maya and Aztec civilization.",
    contextYear: -1000,
  },
  "Teotihuacán": {
    name: "Teotihuacan",
    capital: "Teotihuacan",
    government: "Unknown (likely corporate rule)",
    language: "Uncertain",
    founded: "100 AD",
    collapsed: "550 AD",
    summary:
      "The mysterious metropolis of the Avenue of the Dead — 100,000 residents at its peak, its name an Aztec word meaning 'place where the gods were made'.",
    contextYear: 450,
  },
  Teotihuacàn: {
    name: "Teotihuacan",
    capital: "Teotihuacan",
    government: "Unknown (likely corporate rule)",
    language: "Uncertain",
    founded: "100 AD",
    collapsed: "550 AD",
    summary:
      "The mysterious metropolis of the Avenue of the Dead — 100,000 residents at its peak, its name an Aztec word meaning 'place where the gods were made'.",
    contextYear: 450,
  },
  "United States of America": {
    name: "United States of America",
    capital: "Washington, D.C.",
    government: "Federal republic",
    language: "English",
    religion: "None established",
    founded: "1776 AD",
    leaders: ["George Washington", "Abraham Lincoln"],
    summary:
      "Declared independence from Britain in 1776 and expanded across a continent to become a leading global power by the 20th century.",
    contextYear: 1900,
  },
  "United States": {
    name: "United States",
    capital: "Washington, D.C.",
    government: "Federal republic",
    language: "English",
    religion: "None established",
    founded: "1776 AD",
    summary:
      "Emerged from thirteen British colonies to become a leading global power over the 19th and 20th centuries.",
    contextYear: 1900,
  },
  "New France": {
    name: "New France",
    capital: "Quebec City",
    government: "Colonial administration",
    language: "French",
    religion: "Catholic Christianity",
    founded: "1534 AD",
    collapsed: "1763 AD",
    leaders: ["Samuel de Champlain", "Louis de Buade de Frontenac"],
    summary:
      "The French fur-trading empire of the St. Lawrence and the Mississippi, ceded to Britain and Spain after the Seven Years' War.",
    partOf: "France",
    contextYear: 1740,
  },
  "British Raj": {
    name: "British Raj",
    capital: "Calcutta, later Delhi",
    government: "Colonial administration",
    language: "English, Hindustani",
    religion: "Hinduism, Islam, Sikhism",
    founded: "1858 AD",
    collapsed: "1947 AD",
    leaders: ["Queen Victoria (Empress)", "Lord Curzon"],
    summary:
      "Direct Crown rule over the subcontinent after the 1857 rebellion — the jewel of empire, and the crucible of the independence movement that ended it.",
    partOf: "British Empire",
    contextYear: 1920,
  },
  // ------------------------------------------------------- Africa
  Egypt: {
    name: "Ancient Egypt",
    capital: "Memphis, later Thebes, Alexandria",
    government: "Divine monarchy",
    language: "Ancient Egyptian",
    religion: "Ancient Egyptian religion",
    founded: "3100 BC",
    collapsed: "30 BC",
    leaders: ["Khufu", "Hatshepsut", "Ramses II", "Cleopatra VII"],
    summary:
      "Three thousand years of kingdom along the Nile — the pyramids, hieroglyphs and pharaohs whose monuments outlasted every contemporary state.",
    contextYear: -1280,
  },
  Axum: {
    name: "Kingdom of Aksum",
    capital: "Aksum",
    government: "Kingdom",
    language: "Ge'ez",
    religion: "Ethiopian Orthodox Christianity (from ~330)",
    founded: "100 AD",
    collapsed: "940 AD",
    leaders: ["Ezana of Axum"],
    summary:
      "The Red Sea trading kingdom that minted its own coinage, raised the great stelae of Ethiopia, and adopted Christianity in the 4th century.",
    contextYear: 400,
  },
  Kush: {
    name: "Kingdom of Kush",
    capital: "Kerma, Napata, Meroë",
    government: "Kingdom",
    language: "Meroitic",
    religion: "Egyptian-influenced polytheism",
    founded: "1070 BC",
    collapsed: "550 AD",
    leaders: ["Piye", "Taharqa"],
    summary:
      "The Nubian kingdom that conquered Egypt as its 25th Dynasty and, later, built more pyramids than Egypt ever did at Meroë.",
    contextYear: -700,
  },
  "Empire of Ghana": {
    name: "Ghana Empire",
    capital: "Koumbi Saleh",
    government: "Monarchy",
    language: "Soninke",
    religion: "African traditional, later Islam (court)",
    founded: "~300 AD",
    collapsed: "1240 AD",
    leaders: ["Ghana Wagadu kings"],
    summary:
      "The 'land of gold' between the Sahara and the Niger that grew rich taxing trans-Saharan caravans — not related to the modern republic of the same name.",
    contextYear: 1000,
  },
  Mali: {
    name: "Mali Empire",
    capital: "Niani",
    government: "Empire",
    language: "Mandinka",
    religion: "Islam",
    founded: "1235 AD",
    collapsed: "1600 AD",
    leaders: ["Sundiata Keita", "Mansa Musa"],
    summary:
      "The empire of Mansa Musa — possibly the wealthiest man ever to live — whose pilgrimage to Mecca spent gold so freely it depressed the Cairo market.",
    contextYear: 1337,
  },
  Songhai: {
    name: "Songhai Empire",
    capital: "Gao",
    government: "Empire",
    language: "Songhay",
    religion: "Islam",
    founded: "1464 AD",
    collapsed: "1591 AD",
    leaders: ["Sunni Ali", "Askia the Great"],
    summary:
      "The successor to Mali at the Niger bend, ruling Timbuktu's universities and Saharan trade until a Moroccan army with muskets ended it at Tondibi.",
    contextYear: 1528,
  },
  Carthagenian: {
    name: "Carthaginian Empire",
    capital: "Carthage",
    government: "Republic",
    language: "Punic",
    founded: "814 BC",
    collapsed: "146 BC",
    leaders: ["Hannibal"],
    summary:
      "The Phoenician trading city whose maritime empire rivaled Rome across three Punic Wars, brought down at last by Scipio's legions and the total destruction of 146 BC.",
    contextYear: -200,
  },
  "Seljuk Caliphate": {
    name: "Seljuk Empire",
    capital: "Isfahan, later Rayy",
    government: "Sultanate",
    language: "Oghuz Turkic, Persian",
    religion: "Islam (Sunni)",
    founded: "1037 AD",
    collapsed: "1194 AD",
    leaders: ["Tughril", "Alp Arslan", "Malik-Shah I"],
    summary:
      "Turkic conquerors who swept from the steppe through Persia to Baghdad, humbled Byzantium at Manzikert in 1071, and patronized Omar Khayyam's observatories.",
    contextYear: 1090,
  },
  "Seljuk Empire": {
    name: "Seljuk Empire",
    capital: "Isfahan, later Rayy",
    government: "Sultanate",
    language: "Oghuz Turkic, Persian",
    religion: "Islam (Sunni)",
    founded: "1037 AD",
    collapsed: "1194 AD",
    leaders: ["Tughril", "Alp Arslan", "Malik-Shah I"],
    summary:
      "Turkic conquerors who swept from the steppe through Persia to Baghdad, humbled Byzantium at Manzikert in 1071, and patronized Omar Khayyam's observatories.",
    contextYear: 1090,
  },
  // ------------------------------------------------------- Modern
  USSR: {
    name: "Soviet Union",
    capital: "Moscow",
    government: "One-party socialist state",
    language: "Russian (de facto)",
    religion: "State atheism",
    founded: "1922 AD",
    collapsed: "1991 AD",
    peakArea: "~22,400,000 km²",
    leaders: ["Vladimir Lenin", "Joseph Stalin", "Mikhail Gorbachev"],
    summary:
      "The world's first communist state and a 20th-century superpower, dissolving in 1991 into fifteen independent republics.",
    contextYear: 1960,
  },
  "East Germany": {
    name: "German Democratic Republic",
    capital: "East Berlin",
    government: "One-party socialist state",
    language: "German",
    religion: "State atheism (officially secular)",
    founded: "1949 AD",
    collapsed: "1990 AD",
    leaders: ["Walter Ulbricht", "Erich Honecker"],
    summary:
      "The Soviet-aligned half of divided Germany, walled into its capital in 1961 and dissolved into the Federal Republic in 1990.",
    partOf: "Warsaw Pact",
    contextYear: 1970,
  },
  "West Germany": {
    name: "Federal Republic of Germany",
    capital: "Bonn",
    government: "Federal republic",
    language: "German",
    religion: "Catholic Christianity, Protestant Christianity",
    founded: "1949 AD",
    collapsed: "1990 AD",
    leaders: ["Konrad Adenauer", "Willy Brandt"],
    summary:
      "The western half of divided Germany, whose 'economic miracle' rebuilt it into Europe's industrial anchor before reunification in 1990.",
    contextYear: 1970,
  },
};

// A few narrative aliases so search / event pins can resolve to curated entries
// even when the underlying GeoJSON uses a slightly different property name.
export const EMPIRE_ALIASES: Record<string, string> = {
  "Han Dynasty": "Han",
  Byzantine: "Byzantine Empire",
  Ottoman: "Ottoman Empire",
  "Napoleonic France": "France",
  "Soviet Union": "USSR",
  "Soviet": "USSR",
  "Umayyads": "Umayyad Caliphate",
  "Abbasids": "Abbasid Caliphate",
  "Ancient Egypt": "Egypt",
  "Kievan Rus'": "Kievan Rus",
  "Kingdom of France": "Kingdom of France",
  "Seljuk Empire": "Seljuk Caliphate",
  "Tsardom of Russia": "Tsardom of Muscovy",
  "Mongolian Empire": "Mongol Empire",
};

// Lowercase-fold lookup so accent / case variants in the data (e.g. Cairo vs
// Kairo, "Castilla" vs "Castile") still resolve to the curated dossier.
const FOLDED: Map<string, EmpireInfo> = (() => {
  const m = new Map<string, EmpireInfo>();
  const fold = (s: string) =>
    s
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .trim();

  for (const info of Object.values(EMPIRES)) {
    const k = fold(info.name);
    if (!m.has(k)) m.set(k, info);
  }
  for (const [alias, target] of Object.entries(EMPIRE_ALIASES)) {
    const info = EMPIRES[target];
    if (info && !m.has(fold(alias))) m.set(fold(alias), info);
  }
  return m;
})();

export function getEmpireInfo(rawName: string): EmpireInfo | undefined {
  const exact = EMPIRES[rawName] ?? EMPIRES[EMPIRE_ALIASES[rawName] ?? ""];
  if (exact) return exact;

  const fold = (s: string) =>
    s
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .trim();

  // Try the whole name first, then a possessive-stripped form.
  return (
    FOLDED.get(fold(rawName)) ??
    FOLDED.get(fold(rawName).replace(/'s$/, ""))
  );
}
